### ISSUE TITLE
empty line-end comments cause crash

### ISSUE THREAD

**Issue by jbedard** [msolo/jsonr#1]
Empty line-end comments seem to crash the parser, see example: https://github.com/sourcegraph/sourcegraph/blob/a2e9b12cc9ff7500487592fc185c0cb276b40361/client/web-sveltekit/tsconfig.json

**Comment by msolo** [comment]
It's not because the comment is empty, it's because the lexer expects a single-line comment or a multi-line comment, but several adjacent single line comments do not a multi-line comment make.

That's a precise, but unsatisfying answer and it has to do with some choices about how newlines are handled and how comments are represented in the concrete syntax tree. Those choices are most adequately explained by laziness and performance.

The minimal reproduction is here:
```
{
  "x": null,
  // Line 1
  // Line 2
  // any subsequent comment line comment fails to parse.
  "y": null,
}
```

Using multi-line syntax works as expected:
```
{
  "x": null,
  /*
  Line 1
  Line 2 is just peachy-ducky within a multi-line context.
  */
  "y": null,
}
```

I agree that several single-line comments should be semantically equivalent to a multiline, but I can't think of a simple fix.

**Comment by jbedard** [comment]
I think removing the empty line (but still multiple comments) fixed my use case so I assumed that was the cause 🤷 

Unfortunately it's not my code with the comments so I can't just change the code to workaround it.

**Comment by msolo** [comment]
I thought about it a bit more and made a change to comment lexing that fixes the issue.

62fbfc3a03137f1c1d260acee8a861c3582baf4e
